// Writes src/abi.ts: the JobRegistry functions the SDK calls, cut from the ABI
// that `make bindings` extracts from the compiled contracts. Run from sdk/ in
// the orchestrator checkout, after `make bindings` if the contracts moved.
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = '../pkg/chain/abis/IJobRegistry.json';
const FUNCTIONS = ['deposit', 'depositAndAuthorize', 'prepaidBalanceOf', 'isDelegateAuthorized', 'delegateAllowance'];

const abi: { type: string; name?: string }[] = JSON.parse(readFileSync(SOURCE, 'utf8'));
const picked = FUNCTIONS.map((name) => {
  const entry = abi.find((e) => e.type === 'function' && e.name === name);
  if (!entry) throw new Error(`${SOURCE} has no function ${name}`);
  return entry;
});

writeFileSync(
  'src/abi.ts',
  `// Generated by scripts/abi.ts from ${SOURCE.slice(3)}. Do not edit.\n` +
    `export const jobRegistryAbi = ${JSON.stringify(picked, null, 2)} as const;\n`,
);
