// Writes src/abi.ts: the JobRegistry functions the SDK calls, cut from the
// JobRegistry's ABI (a JSON array) when the contracts change.
//
//   npm run abi -- path/to/IJobRegistry.json
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = process.argv[2];
if (!SOURCE) throw new Error('usage: npm run abi -- path/to/IJobRegistry.json');
const FUNCTIONS = ['deposit', 'depositAndAuthorize', 'prepaidBalanceOf', 'isDelegateAuthorized', 'delegateAllowance'];

const abi: { type: string; name?: string }[] = JSON.parse(readFileSync(SOURCE, 'utf8'));
const picked = FUNCTIONS.map((name) => {
  const entry = abi.find((e) => e.type === 'function' && e.name === name);
  if (!entry) throw new Error(`${SOURCE} has no function ${name}`);
  return entry;
});

writeFileSync(
  'src/abi.ts',
  '// Generated by scripts/abi.ts from the JobRegistry ABI. Do not edit.\n' +
    `export const jobRegistryAbi = ${JSON.stringify(picked, null, 2)} as const;\n`,
);
